apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stock-search
  labels:
    app: stock-search
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: stock-search
    spec:
      containers:
        - name: stock-search
          image: eu.gcr.io/mimir-185212/stock-search:0.1
          ports:
            - name: svc-port
              containerPort: 8080
          env:
            - name: SERVICE_PORT
              value: "8080"
            - name: DB_HOST
              value: mimir-db
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: streamlistener
            - name: DB_USERNAME
              value: stocksearch
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: stocksearch.password
            - name: ADMIN_USER_ID
              valueFrom:
                secretKeyRef:
                  name: admin-users
                  key: stocksearch.id
            - name: TOKEN_SECRETS_FILE
              values: "/etc/mimir/token_secrets.json"
          volumeMounts:
            - name: token-secrets
              mountPath: /etc/mimir/token_secrets.json
              subPath: token_secrets.json
          livenessProbe:
            httpGet:
              path: /health
              port: svc-port
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: svc-port
            initialDelaySeconds: 25
          imagePullPolicy: Always
      volumes:
        - name: token-secrets
          secret:
            secretName: token-secret
            items:
              - key: content
                path: token_secrets.json
      imagePullSecrets:
        - name: gcr-json-key
